source 'https://rubygems.org'

gem 'rails', '~> 6.1.0'
gem 'sqlite3'
gem 'puma'
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'
gem 'devise'
gem 'rspec-rails', '~> 4.0.0', group: [:development, :test]
gem 'factory_bot_rails', group: [:development, :test]
gem 'faker', group: [:development, :test]

# Other gems can be added below as needed.