databases:
  - name: zona44-db
    databaseName: zona44_production
    user: zona44_user
    region: oregon
    plan: free 

services:
  - type: web
    name: zona44-backend
    runtime: ruby
    rootDir: backend
    region: oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zona44-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
