source "https://rubygems.org"

# --- Core Rails ---
gem "rails", "~> 8.0.2"
gem "puma", ">= 5.0"
gem "pg", "~> 1.1"
gem "propshaft"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"

# --- Internacionalización ---
gem "rails-i18n"
gem "route_translator"

# --- Autenticación y seguridad ---
gem "devise"
gem "omniauth-google-oauth2"
gem "omniauth-rails_csrf_protection"
gem "google-id-token"

# --- Configuración ---
gem "dotenv-rails"

# --- Imágenes y archivos ---
gem "image_processing", "~> 1.2"
gem "mini_magick"
gem "cloudinary", "~> 1.25"
gem "activestorage-cloudinary-service", "~> 0.2.0"

# --- CORS ---
gem "rack-cors", require: "rack/cors"

# --- HTTP Client ---
gem "httparty"

# --- Cache, colas y websockets ---

# --- Optimización y despliegue ---
gem "bootsnap", require: false
gem "kamal", require: false
gem "thruster", require: false

# --- Windows y JRuby ---
gem "tzinfo-data", platforms: %i[windows jruby]

# --- OpenIA ---
gem "ruby-openai"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
  gem "i18n-tasks"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end


gem "whenever", "~> 1.0"
